package edu.oopgroup2.ppe.gui.admin;

import edu.oopgroup2.ppe.configuration.DropdownUtils;
import edu.oopgroup2.ppe.model.inventory.InventoryManagement;
import javax.swing.JOptionPane;

public class PopUp_IM_AddNewItem extends javax.swing.JFrame {

    private GUI_InventoryManagement parent;
    /**
     * Creates new form PopUp_IM_AddNewItem
     * @param parent
     */
    public PopUp_IM_AddNewItem(GUI_InventoryManagement parent) {
        this.parent = parent;
        initComponents();
        IM_btn_Cancel.addActionListener(e -> dispose());
        DropdownUtils.populateSupplierIDDropdown(IM_cb_SupplierID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        IM_lbl_Quantity = new javax.swing.JLabel();
        IM_lbl_ItemCode = new javax.swing.JLabel();
        IM_lbl_ItemName = new javax.swing.JLabel();
        IM_lbl_SupplierID = new javax.swing.JLabel();
        IM_tf_ItemName = new javax.swing.JTextField();
        IM_tf_ItemCode = new javax.swing.JTextField();
        IM_tf_Quantity = new javax.swing.JTextField();
        IM_cb_SupplierID = new javax.swing.JComboBox<>();
        IM_btn_Save = new javax.swing.JButton();
        IM_btn_Cancel = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(4, 99, 174));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add New Item");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 0, 185, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 70));

        jPanel1.setBackground(new java.awt.Color(224, 247, 250));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IM_lbl_Quantity.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IM_lbl_Quantity.setText("Quantity:");
        jPanel1.add(IM_lbl_Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 215, 80, 20));

        IM_lbl_ItemCode.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IM_lbl_ItemCode.setText("Item ID:");
        jPanel1.add(IM_lbl_ItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 95, 80, 20));

        IM_lbl_ItemName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IM_lbl_ItemName.setText("Item Name:");
        jPanel1.add(IM_lbl_ItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 135, 80, 20));

        IM_lbl_SupplierID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IM_lbl_SupplierID.setText("Supplier ID:");
        jPanel1.add(IM_lbl_SupplierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 175, 80, 20));
        jPanel1.add(IM_tf_ItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 132, 180, -1));
        jPanel1.add(IM_tf_ItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 92, 180, -1));

        IM_tf_Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IM_tf_QuantityActionPerformed(evt);
            }
        });
        jPanel1.add(IM_tf_Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 212, 180, -1));

        IM_cb_SupplierID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        IM_cb_SupplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IM_cb_SupplierIDActionPerformed(evt);
            }
        });
        jPanel1.add(IM_cb_SupplierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 172, 180, 25));

        IM_btn_Save.setFont(new java.awt.Font("Tw Cen MT", 2, 15)); // NOI18N
        IM_btn_Save.setText("Save");
        IM_btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IM_btn_SaveActionPerformed(evt);
            }
        });
        jPanel1.add(IM_btn_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 255, 80, 28));

        IM_btn_Cancel.setFont(new java.awt.Font("Tw Cen MT", 2, 15)); // NOI18N
        IM_btn_Cancel.setText("Cancel");
        IM_btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IM_btn_CancelActionPerformed(evt);
            }
        });
        jPanel1.add(IM_btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 255, 80, 28));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IM_cb_SupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IM_cb_SupplierIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IM_cb_SupplierIDActionPerformed

    private void IM_btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IM_btn_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IM_btn_CancelActionPerformed

    private void IM_btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IM_btn_SaveActionPerformed
        // TODO add your handling code here:
        String itemCode = IM_tf_ItemCode.getText().trim().toUpperCase();
        String itemName = IM_tf_ItemName.getText().trim();
        String supplierID = (String) IM_cb_SupplierID.getSelectedItem();
        int quantity;
        try {
            quantity = Integer.parseInt(IM_tf_Quantity.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantity must be a valid number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String result = InventoryManagement.addPPEItem(itemCode, itemName, supplierID, quantity);
        JOptionPane.showMessageDialog(this, result, "Add New Item", JOptionPane.INFORMATION_MESSAGE);
        if (result.startsWith("PPE item added successfully")) {
            parent.loadInventoryData();
            dispose();
        }
    }//GEN-LAST:event_IM_btn_SaveActionPerformed

    private void IM_tf_QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IM_tf_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IM_tf_QuantityActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IM_btn_Cancel;
    private javax.swing.JButton IM_btn_Save;
    private javax.swing.JComboBox<String> IM_cb_SupplierID;
    private javax.swing.JLabel IM_lbl_ItemCode;
    private javax.swing.JLabel IM_lbl_ItemName;
    private javax.swing.JLabel IM_lbl_Quantity;
    private javax.swing.JLabel IM_lbl_SupplierID;
    private javax.swing.JTextField IM_tf_ItemCode;
    private javax.swing.JTextField IM_tf_ItemName;
    private javax.swing.JTextField IM_tf_Quantity;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
