package edu.oopgroup2.ppe.gui;

import edu.oopgroup2.ppe.gui.staff.GUI_StaffDashboard;
import edu.oopgroup2.ppe.authentication.LoginManagement;
import edu.oopgroup2.ppe.configuration.UserSession;
import edu.oopgroup2.ppe.gui.admin.GUI_AdminDashboard;
import javax.swing.JOptionPane;

public class GUI_Login extends javax.swing.JFrame {
    private int loginAttempts = 0;
    /**
     * Creates new form GUI_Login
     */
    public GUI_Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private void clearFields() {
        tf_EmpId.setText("");
        pf_Login.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_LoginPage = new javax.swing.JLabel();
        lbl_EmpId = new javax.swing.JLabel();
        tf_EmpId = new javax.swing.JTextField();
        lbl_Password = new javax.swing.JLabel();
        pf_Login = new javax.swing.JPasswordField();
        btn_Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(224, 247, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 265));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 265));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 20)); // NOI18N
        jLabel1.setText("PPE Inventory Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 33, -1, -1));

        lbl_LoginPage.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        lbl_LoginPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LoginPage.setText("Login Page");
        lbl_LoginPage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lbl_LoginPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 72, -1, -1));

        lbl_EmpId.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_EmpId.setText("Employee ID:");
        jPanel1.add(lbl_EmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 114, -1, -1));

        tf_EmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_EmpIdActionPerformed(evt);
            }
        });
        jPanel1.add(tf_EmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 112, 152, -1));

        lbl_Password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_Password.setText("Password     :");
        jPanel1.add(lbl_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 171, -1, -1));

        pf_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(pf_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 169, 152, -1));

        btn_Login.setText("Login");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 265));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
        String userID, password;
        userID = tf_EmpId.getText();
        password = pf_Login.getText();
        String[] userDetails = LoginManagement.authenticate(userID, password);
        if (userDetails != null) {
            JOptionPane.showMessageDialog(this, "Login Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            UserSession.setUser(userDetails[0], userDetails[1]);
            if (userDetails[2].equalsIgnoreCase("Admin")) {
                new GUI_AdminDashboard().setVisible(true);
            } else {
                new GUI_StaffDashboard().setVisible(true);
            }
            this.dispose();
        } else {
            clearFields();
            loginAttempts++;
            JOptionPane.showMessageDialog(this, "Invalid credentials. Attempts left: " + (3 - loginAttempts), "Login Failed", JOptionPane.ERROR_MESSAGE);
            if (loginAttempts >= 3) {
                JOptionPane.showMessageDialog(this, "Too many failed attempts! Exiting...", "Access Denied", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void tf_EmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_EmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EmpIdActionPerformed

    private void pf_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_EmpId;
    private javax.swing.JLabel lbl_LoginPage;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JPasswordField pf_Login;
    private javax.swing.JTextField tf_EmpId;
    // End of variables declaration//GEN-END:variables
}
